package com.example.debt.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.debt.entity.RewardContent;

import com.example.debt.entity.RewardContentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rewardContentDaoConfig;

    private final RewardContentDao rewardContentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rewardContentDaoConfig = daoConfigMap.get(RewardContentDao.class).clone();
        rewardContentDaoConfig.initIdentityScope(type);

        rewardContentDao = new RewardContentDao(rewardContentDaoConfig, this);

        registerDao(RewardContent.class, rewardContentDao);
    }
    
    public void clear() {
        rewardContentDaoConfig.clearIdentityScope();
    }

    public RewardContentDao getRewardContentDao() {
        return rewardContentDao;
    }

}
