package com.example.debt.entity;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rewardContentDaoConfig;
    private final DaoConfig rewardRecordDaoConfig;

    private final RewardContentDao rewardContentDao;
    private final RewardRecordDao rewardRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rewardContentDaoConfig = daoConfigMap.get(RewardContentDao.class).clone();
        rewardContentDaoConfig.initIdentityScope(type);

        rewardRecordDaoConfig = daoConfigMap.get(RewardRecordDao.class).clone();
        rewardRecordDaoConfig.initIdentityScope(type);

        rewardContentDao = new RewardContentDao(rewardContentDaoConfig, this);
        rewardRecordDao = new RewardRecordDao(rewardRecordDaoConfig, this);

        registerDao(RewardContent.class, rewardContentDao);
        registerDao(RewardRecord.class, rewardRecordDao);
    }
    
    public void clear() {
        rewardContentDaoConfig.clearIdentityScope();
        rewardRecordDaoConfig.clearIdentityScope();
    }

    public RewardContentDao getRewardContentDao() {
        return rewardContentDao;
    }

    public RewardRecordDao getRewardRecordDao() {
        return rewardRecordDao;
    }

}
